### ISSUE TITLE
Errors occurred when executting "cordova run android"

### ISSUE THREAD

**Issue by litao10422** [dekimasoon/vue-cli-plugin-cordova#10]
The following errors occur when I execute the command "cordova run android".

```
ANDROID_HOME=C:\Users\litao\AppData\Roaming\npm\node_modules\cordova\bin\cordova
JAVA_HOME=C:\Program Files\java\jdk-10.0.1
(node:109244) UnhandledPromiseRejectionWarning: CordovaError: Requirements check failed for JDK 1.8 or greater
    at C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\lib\check_reqs.js:370:19
    at _fulfilled (C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:854:54)
    at self.promiseDispatch.done (C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:883:30)
    at Promise.promise.promiseDispatch (C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:816:13)
    at C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:624:44
    at runSingle (C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:137:13)
    at flush (C:\MyDvlp\Cordova\vue-cordova-pj01\platforms\android\cordova\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:109244) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:109244) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I checked my JDK environment, there is not any other versions there.
```
    Java
        jdk-10.0.1
        jre-10.0.1
```
Please teach how to deal with this issue. 
Thank you very much!

**Comment by dekimasoon** [comment]
Hi @litao10422 .
Excuse pool documentation 😢 

I think the error said `Your JDK is too old, you need v1.8 or greater`.
So please try`$cordova requirements` command, and make sure all Cordova requirements are installed properly.

Hope you get through it!

**Comment by litao10422** [comment]
My JDK is the latest one, JDK 10. I even consider to uninstall JKD 10 and install JDK 8 (JDK 1.8).
anyway I'll try `$cordova requirements`.
I like  this plugin and thank you for your quick reply.

**Comment by litao10422** [comment]
```
C:\MyDvlp\Cordova\vue-cordova-pj01>cordova requirements
Android Studio project detected

Requirements check results for android:
Java JDK: installed
Android SDK: installed true
Android target: not installed
```

I think I need to set Android target.

**Comment by dekimasoon** [comment]
> My JDK is the latest one, JDK 10. I even consider to uninstall JKD 10 and install JDK 8 (JDK 1.8).

You are right. I was wrong, and agree to trying reinstall jdk 1.8.

Please let me know if you figure out what makes that error. Thank you for trying this plugin.

**Comment by litao10422** [comment]
I installed JDK 8 (jdk1.8.0_172) and JDK 10 (jdk-10.0.1).

Execute "cordova build android" when setting "JAVA_HOME=C:\Program Files\Java\jdk1.8.0_172", a workable apk is created and I can run it on my smartphone.

The error still occurs when setting "JAVA_HOME=C:\Program Files\Java\jdk-10.0.1".

Is this Cordova's problem?

**Comment by dekimasoon** [comment]
I am glad to hear that the build went through :tada:

> The error still occurs when setting "JAVA_HOME=C:\Program Files\Java\jdk-10.0.1".
> Is this Cordova's problem?

Yes, it is actually Android's problem. The Android seems not to support jdk10. 
https://github.com/ionic-team/ionic-app-scripts/issues/1424#issuecomment-384869781

**Comment by litao10422** [comment]
Thank you for the information. Hope the Android SDK fixes the issue to support jdk10.
I like this plugin, it's easy to use.
