### ISSUE TITLE
Vuetify support.

### ISSUE THREAD

**Issue by cairin** [dekimasoon/vue-cli-plugin-cordova#13]
I'm a collaborator on [vuetifyjs/cordova](https://github.com/vuetifyjs/cordova), and I was wondering if I could help with optimising a few things and creating a better first application template.

We would love to have your package as our default cordova template for Vuetify to replace our previous cordova template.

**Comment by dekimasoon** [comment]
Thank you for your proposal. It is really grateful. I read vue-cli-plugin-vuetify's README.md and I feel shameful it says "Cordova (not working yet)". :cry:

I think I should omit the vuetify part from this plugin and make it works well with the vue-cli-plugin-vuetify and even other ui-framework's plugins.

Please let me hear what you think.

**Comment by cairinmichie** [comment]
> I think I should omit the vuetify part from this plugin and make it works well with the vue-cli-plugin-vuetify and even other ui-framework's plugins.

I think this is probably the best way to do it, for this plugin. Let me know if you need help testing.

**Comment by am** [comment]
My 2c, please consider vuetify as an optional dependency, since vue-cli-plugin-cordova may be useful also in cases where vuetify is not needed. Dragging dependencies that are not used its not optimal. This was also mentioned on other issue: https://github.com/dekimasoon/vue-cli-plugin-cordova/issues/26

**Comment by m0dch3n** [comment]
Hi, just jfyi, I created another cordova plugin, free of any unnecessary dependencies

https://github.com/m0dch3n/vue-cli-plugin-cordova
