### ISSUE TITLE
How can we add plugin to work?

### ISSUE THREAD

**Issue by Akirami** [dekimasoon/vue-cli-plugin-cordova#18]
Hi,

I added cordova-plugin-file and the browser return `ReferenceError: cordova is not defined` and when i add to index.html `<script src="../cordova.js"></script>` it return `SyntaxError: expected expression, got '<'`

So is there a good way to add this to my project ?

Note that i had the plugin just after `vue add cordova` on a fresh install, put some code in a file and 
call it after deviceready event.

here is my code

```
if (navigator.userAgent.match(/(iPhone|iPod|iPad|Android|BlackBerry)/)) {
    document.addEventListener('deviceready', onDeviceReady, false)
} else {
    setTimeout(function () {
        onDeviceReady()
    }, 1500)
}
function checkIfFileExists (path, fileName) {
    return new Promise(function (resolve, reject) {
        window.resolveLocalFileSystemURL(path + fileName, fileExists, fileDoesNotExist, fail)
        function fileExists () {
            return true
        }
        function fileDoesNotExist () {
            return false
        }
        resolve(fileExists())
        reject(fileDoesNotExist())
    })
}

function onDeviceReady () {
    checkIfFileExists(cordova.file.dataDirectory, 'SnDConfig.json').then(function (file) {
        if (file) {
            readFromTextFile(cordova.file.dataDirectory, 'SnDConfig.json').then(function (data) {
                cfgData = JSON.parse(data)
                function getLang (type) {
                    let language = {
                        'Français': 'fr_FR',
                        'English': 'en_US'
                    }
                    return language[type]
                }
                let lang = getLang(cfgData.language)
                console.log('0: ' + lang)
                /* getFilesList() */
            })
        } else {
            console.log('0: ')
        }
    }).catch(function (e) {
        console.log(e)
    })
}
```

**Comment by dekimasoon** [comment]
Hi, @Akirami.
Just by executing the following command, it should be able to install normally.
```sh
$ cordova plugin add cordova-plugin-file  # install file plugin
$ npm run cordova-serve                   # rebuild project
```
I made a sample repository. 
https://github.com/dekimasoon/vue-cordova-file-plugin-sample

If it doesn't work, I really need the repo I can clone to reproduce your issue.

**Comment by Akirami** [comment]
Hi @dekimasoon

I think you can close for now, i'm not sure if it's your module or vue-cli-service that have a problem with my installation.

Sometime `cordova build browser` work, sometime not and i don't know why, it's like if some part of the complete installation was not found in the folders (vue-cli service does not find build script).

When i have more info I will come back.

Also, this module is actually the best I found for working with cordova and Vue.js, you did a very good job, especially with the livereload that will save me a lot of time. Thank you very much.

> I really need the repo I can clone to reproduce your issue.
And i really need to commit my first repo ;)

**Comment by dekimasoon** [comment]
> When i have more info I will come back.

I got it. 

> Also, this module is actually the best I found for working with cordova and Vue.js, you did a very good job, especially with the livereload that will save me a lot of time. Thank you very much.

Your words are very encouraging. Thanks!!

**Comment by Akirami** [comment]
Hi @dekimasoon,

I found one of my mistake... and yours ;)

In https://github.com/dekimasoon/vue-cli-plugin-cordova/blob/master/docs/StartGuide.md

There is a typo : Browser Platform/iOS Platform/Android Platform>Production Build>`npm run corodva-build`

Instead of : `npm run cordova-build`

Have a good day / evening.
