### ISSUE TITLE
Typo in StartGuide.md

### ISSUE THREAD

**Issue by Akirami** [dekimasoon/vue-cli-plugin-cordova#21]
https://github.com/dekimasoon/vue-cli-plugin-cordova/blob/master/docs/StartGuide.md

Actually

>npm run corodva-build

Instead of 

>npm run cordova-build

Each in production build section (Browser/iOS/Android)

**Comment by dekimasoon** [comment]
@Akirami Thank you for pointing out! I fixed it.
