### ISSUE TITLE
cordova plugins?

### ISSUE THREAD

**Issue by rpdiss** [dekimasoon/vue-cli-plugin-cordova#22]
how do u access cordova plugins?

**Comment by dekimasoon** [comment]
It depends on which plugin you use.
This `vue-cli-plugin-corodova` does nothing on that point.

Please check my file-plugin sample.
https://github.com/dekimasoon/vue-cordova-file-plugin-sample/commit/5ced4691867a6c635bab93d645facadee847d331

**Comment by dekimasoon** [comment]
Close once. If there is an update please reopen it!
