### ISSUE TITLE
'Avoid modifying webpack output.publicPath directly' error on npm run cordova-build

### ISSUE THREAD

**Issue by bouchezb** [dekimasoon/vue-cli-plugin-cordova#23]
Hi, i tryied to follow these steps 

https://onsen.io/v2/guide/vue/#vue-js

and ended un with an error on `npm run cordova-build`

```
> vue-cli-service build --dest www


⠋  Building for production... ERROR  Error:

Configuration Error: Avoid modifying webpack output.publicPath directly. Use the "baseUrl" option instead.

Error:

Configuration Error: Avoid modifying webpack output.publicPath directly. Use the "baseUrl" option instead.
```
I think this is a `vue-cli` issue, but i want to know if you experienced it and how to bypass this issue.

Thanks.

**Comment by blackholegalaxy** [comment]
same here.

**Comment by dekimasoon** [comment]
Thank you for reporting issue.
I have to update this plugin to support vue-cli3-rc.
I promise to find time to respond. Sorry I made you wait

**Comment by evinkuraga** [comment]
I don't think this was updated yet. Had to do a few work arounds in order to get a fresh app to work.

**Comment by joel-chu** [comment]
I got to the step 

```sh
npm run cordova-build
```

Then 

```sh
Building for production... ERROR  Error: 
               
Configuration Error: Avoid modifying webpack output.publicPath directly. Use the "baseUrl" option instead.
               
Error: 

Configuration Error: Avoid modifying webpack output.publicPath directly. Use the "baseUrl" option instead.
```

Then a bunch of error throw from @vue/cli-service/lib/util/validateWebpackConfig.js

**Comment by dekimasoon** [comment]
Sorry my too slow response. I finally fixed the issue.
Please check the v1.0.0-beta.9.
